[package]
name = "oops"
version = "0.1.0"
edition = "2018"
description = "Orhun's obscure pastebin server"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]

[dependencies]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
