[package]
name = "rustypaste"
version = "0.2.0"
edition = "2018"
description = "A minimal file upload/pastebin service"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/orhun/rustypaste"
repository = "https://github.com/orhun/rustypaste"
keywords = ["paste", "pastebin", "upload"]
categories = ["web-programming::http-server"]
include = ["src/**/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
actix-web = "3.3.2"
actix-multipart = "0.3.0"
actix-files = "0.5.0"
env_logger = "0.9.0"
log = "0.4.14"
serde = "1.0.127"
futures-util = "0.3.16"
petname = "1.1.0"
rand = "0.8.4"
dotenv = "0.15.0"
url = "2.2.2"

[dependencies.config]
version = "0.11.0"
default-features = false
features = ["toml", "yaml"]

[dependencies.byte-unit]
version = "4.0.12"
features = ["serde"]

[dependencies.infer]
version = "0.5.0"
default-features = false

[dev-dependencies]
actix-rt = "2.2.0"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
