[package]
name = "oops"
version = "0.1.0"
edition = "2018"
description = "An obscure pastebin server"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]

[dependencies]
actix-web = "3.3.2"
actix-multipart = "0.3.0"
actix-files = "0.5.0"
env_logger = "0.9.0"
log = "0.4.14"
serde = "1.0.126"
futures-util = "0.3.15"
config = "0.11.0"
petname = "1.1.0"
rand = "0.8.4"

[dependencies.byte-unit]
version = "4.0.12"
features = ["serde"]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
