[server]
address="127.0.0.1:8000"
#workers=4
max_content_length="10MB"
upload_path="./upload"

[paste]
random_url = { enabled = true, type = "petname", words = 2, separator = "-" }
#random_url = { enabled = true, type = "alphanumeric", length = 8 }
default_extension = "txt"
