[server]
address="127.0.0.1:8000"
#workers=4
max_content_length="10MB"
upload_path="./upload"
#auth_token="" # OOPS_SERVER__AUTH_TOKEN=

[paste]
pet_names = { enabled = true, words = 2, separator = "-" }
random = { enabled = false, length = 8 }
default_extension = "txt"
