[server]
address="127.0.0.1:8000"
#workers=4
max_content_length="10MB"
upload_path="./upload"

[paste]
random_url = { enabled = true, words = 2, separator = "-", type = "petname" }
#random_url = { enabled = true, length = 8, type = "alphanumeric" }
default_extension = "txt"
