version: "3.6"
services:
  server:
    image: orhunp/rustypaste:${IMAGE_TAG:-latest}
    build: .
    container_name: rustypaste
    restart: always
    environment:
      - RUST_LOG=debug
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./upload/:/app/upload
      - ./config.toml:/app/config.toml
